Set mypy_path to the src directory
Set [mypy_path] in the configuration file pointing it to the `src` directory.
This is required to avoid errors about missing imports related to your package
when mypy is invoked on files located outside of the package, such as modules in
the test suite. For example, pre-commit runs mypy on staged files only, so this
would be a common issue with our mypy pre-commit hook.

Here is an example of an error message resulting from running mypy on a test
module without mypy_path:

```
tests/test_console.py:5:1: error: Skipping analyzing 'cookiecutter_hypermodern_python_instance': found module but no type hints or library stubs  [import]
    from cookiecutter_hypermodern_python_instance import console
    ^
tests/test_console.py:5:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

[mypy_path]: https://mypy.readthedocs.io/en/stable/config_file.html#config-file-import-discovery