Allow untyped decorators in noxfile.py
The @nox.session decorator is untyped, because mypy cannot import type
information for nox. This leads to errors like the following:

  noxfile.py: note: At top level:
  noxfile.py:111:2: error: Untyped decorator makes function "black" untyped  [misc]
      @nox.session(python="3.8")
      ^