Allow untyped decorators in tests
The @pytest.fixture decorator is untyped, because mypy cannot import type
information for pytest. This leads to the following error:

  tests/test_console.py:8:2: error: Untyped decorator makes function "runner" untyped  [misc]
      @pytest.fixture
      ^