Use sys.version_info instead of try...except ImportError
Importing under try...except forces us to apply a `type: ignore` comment to
the try branch for Python versions without the module. This comment, in turn,
leads to an error in strict mode, for the Python version having the module:

  src/cookiecutter_hypermodern_python_instance/__init__.py:3: error: unused 'type: ignore' comment
          from importlib.metadata import version, PackageNotFoundError  # type: ignore
          ^